name: Test Lint
#on: [push, workflow_dispatch]
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint Action
        run: npm run lint
      - name: Test code
        run: npm run
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo 'Deploying...'
